name: pseudosejahtera
description: An app that mocks the MySejahtera app, which is developed by the Malaysian Government to mitigate the country's COVID-19 pandemic. This mock is strictly for educational purposes and is not meant to be used in real world situations.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_statusbarcolor_ns: ^0.4.0
  intl: ^0.17.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: PseudoSejahteraIcons
      fonts:
        - asset: assets/fonts/PseudoSejahteraIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
