/// Flutter icons PseudoSejahteraIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PseudoSejahteraIcons
///      fonts:
///       - asset: fonts/PseudoSejahteraIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PseudoSejahteraIcons {
  PseudoSejahteraIcons._();

  static const _kFontFam = 'PseudoSejahteraIcons';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData vaccines_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
